project:
  type: website
  output-dir: docs

website:
  title: "Xochitl Ortiz Ross"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - about.qmd
      

format:
  html:
    theme: 
      light: cosmo
      dark: Darkly
    css: styles.css
    toc: true

editor: visual

